dist: trusty
sudo: required

services:
- docker

before_deploy:
- ./scripts/setup_kubernetes.sh ${TRAVIS_BRANCH}

deploy:
  - provider: script
    skip_cleanup: true
    script: ./scripts/deploy.sh ${TRAVIS_BRANCH} ${TRAVIS_COMMIT::8}
    on:
      branch: master
